package riddle_game;

public class RiddleData {
    public static Riddle[] getRiddles() {
        return new Riddle[] {
                new Riddle("Ağzım olmadan konuşurum ve kulaklarım olmadan duyarım. Vücudum yok ama rüzgarla canlanırım. Ben neyim?", "Yankı", "İpucu: Ses yansıtma yeteneğiyle bilinir."),
                new Riddle("Ne kadar çok alırsan o kadar çok geride bırakırım. Ben neyim?", "Ayak izleri", "İpucu: Yürüdüğünüzde geride bıraktığınız şey."),
                new Riddle("Canlı değilim ama büyüyebilirim; ciğerlerim yok ama havaya ihtiyacım var; ağzım yok ama su beni öldürür. Ben neyim?", "Ateş", "İpucu: Isı ve ışık üretir."),
                new Riddle("Geceleri gökyüzünde parlarım, ama bir yıldız değilim. Ben neyim?", "Ay", "İpucu: Dünya'nın doğal uydusudur."),
                new Riddle("Bir kapı gibi açılırım, ama bir kapı değilim. Anahtarım yoktur ama açılırım. Ben neyim?", "Kitap", "İpucu: Bilgi içerir ve sayfaları vardır."),
                new Riddle("Gün içinde uzarım, ama gece kaybolurum. Ben neyim?", "Gölge", "İpucu: Işık varken oluşur."),
                new Riddle("İki ucum var ama sonum yok. Ben neyim?", "Yol", "İpucu: Araçlar üzerinde hareket eder."),
                new Riddle("Hangi ayda 28 gün vardır?", "Hepsi", "İpucu: Tüm aylarda 28 gün bulunur."),
                new Riddle("Sadece bir tane elma var ama onu paylaştığında birden fazla kişi yiyebilir. Ben neyim?", "Tohum", "İpucu: Paylaşıldığında çoğalır."),
                new Riddle("Duvarda asılı bir resim vardır ve adam 'benim babamın oğlu' diyor ama o adamın babasının hiç oğlu yok. Kimdir bu?", "Kendisi", "İpucu: Aynı kişi."),
                new Riddle("Bir fıçı su ağırlığında ama içinde ne kadar çok delik açarsanız o kadar hafif olur. Ben neyim?", "Sünger", "İpucu: Delikler arttıkça hafifler."),
                new Riddle("Gün geçtikçe büyür ve yıpranır ama yaşlanmaz. Ben neyim?", "Ayakkabı", "İpucu: Ayaklarınıza giyersiniz."),
                new Riddle("Gözünüz kapalıyken bile gördüğünüz şey nedir?", "Rüya", "İpucu: Uyurken görülür."),
                new Riddle("Ateşli ve canlı, ama suyu gördüğünde hemen ölür. Ben neyim?", "Alev", "İpucu: Suyu sevmez."),
                new Riddle("Gözlerim var ama göremem. Ben neyim?", "Patates", "İpucu: Kök sebzedir."),
                new Riddle("Hem yürüyebilir hem de uçamaz. Hem uçamaz hem de yürüyemez. Ben neyim?", "Balık", "İpucu: Suda yaşar."),
                new Riddle("Sadece bir kere sahneye çıkar ve tüm hayatını orada geçirir. Ben neyim?", "İnsan", "İpucu: Hayat sahnesinde oynar."),
                new Riddle("Bir evim var ama içinde oturamam. Ben neyim?", "Salatalık", "İpucu: Sebzedir."),
                new Riddle("Gözle görülmez ama kırılabilir. Ben neyim?", "Güven", "İpucu: İnançla ilgilidir."),
                new Riddle("Siyah beyaz ama yanlış cevapla renklenir. Ben neyim?", "Satranç", "İpucu: Tahta oyunu."),
                new Riddle("İki kardeşim var ama aynı yaşta değiliz. Ben neyim?", "Ay", "İpucu: Güneş ve Dünya'nın kardeşi."),
                new Riddle("Çiftlikte yaşıyorum ama çorap giyemem. Ben neyim?", "Horoz", "İpucu: Sabahları öter."),
                new Riddle("Her zaman ileriye giderim ama asla geri dönmem. Ben neyim?", "Zaman", "İpucu: Durmaz."),
                new Riddle("Her şeyi içeride tutarım ama kapak yoktur. Ben neyim?", "Ağız", "İpucu: Yemek yerken açılır."),
                new Riddle("Yükseklere çıkmak isterim ama ayaklarım yok. Ben neyim?", "Duman", "İpucu: Ateşin sonucudur."),
                new Riddle("Konuşamam ama hep dinlerim. Ben neyim?", "Kulak", "İpucu: Sesleri alır."),
                new Riddle("Gün doğumunda doğarım, gün batımında ölürüm. Ben neyim?", "Gölge", "İpucu: Işığın arkadaşıdır."),
                new Riddle("Beni bir kere kırarsan, her zaman daha kırılgan olurum. Ben neyim?", "Kalp", "İpucu: Duyguların evidir."),
                new Riddle("Uçabilirim ama kanatlarım yok. Ben neyim?", "Zaman", "İpucu: Uçar gider."),
                new Riddle("Sabah yürürüm, öğlen dururum, akşam çökerim. Ben neyim?", "Gölge", "İpucu: Güneşle hareket eder."),
                new Riddle("Karnımda bin tane balık var ama su yok. Ben neyim?", "Balıkçı ağı", "İpucu: Denizcilik ile ilgilidir."),
                new Riddle("Ne kadar çok çekersem o kadar küçülürüm. Ben neyim?", "Sigara", "İpucu: İçildiğinde biter."),
                new Riddle("Gözle görülmez, el ile tutulmaz ama insanı hareket ettirir. Ben neyim?", "Rüzgar", "İpucu: Doğanın nefesi."),
                new Riddle("Beni kesersen her yerim yeşerir. Ben neyim?", "Çim", "İpucu: Bahçelerde bulunur."),
                new Riddle("Gözüm var ama görmem. Ayağım var ama yürümem. Ben neyim?", "İğne", "İpucu: Dikim işinde kullanılır."),
                new Riddle("Canlı değilim ama her zaman büyürüm. Ben neyim?", "Haber", "İpucu: Bilgilendirir."),
                new Riddle("Her zaman yanımda olursun ama beni asla göremezsin. Ben neyim?", "Gölge", "İpucu: Işıkla var olur."),
                new Riddle("Gözlerim var ama ağlayamam. Ben neyim?", "Soğan", "İpucu: Kesildiğinde gözleri yaşartır."),
                new Riddle("Güneşten kaçarım ama yağmurdan kaçamam. Ben neyim?", "Gölge", "İpucu: Işıkla var olur."),
                new Riddle("Gözleri olan ama görmeyen nedir?", "İğne", "İpucu: Dikiş için kullanılır."),
                new Riddle("Beni kırmadan asla kullanamazsınız. Ben neyim?", "Yumurta", "İpucu: Kahvaltının vazgeçilmezidir."),
                new Riddle("Güneş ışığında doğar, gölgeyle kaybolur. Ben neyim?", "Gölge", "İpucu: Işıkla var olur."),
                new Riddle("Hangi iki anahtar, herhangi bir kapıyı açmaz?", "Piyano tuşları", "İpucu: Müzikle ilgilidir."),
                new Riddle("Tüm gün çalışırım, gece dinlenirim. Ben neyim?", "Ayakkabı", "İpucu: Ayaklarınıza giyersiniz."),
                new Riddle("Hangi kelime, kütüphanede okunmaz?", "Sessizlik", "İpucu: Gürültüsüz bir durumu ifade eder."),
                new Riddle("Sadece bir kez yapılır, ama sonsuza kadar sürer. Ben neyim?", "Hata", "İpucu: Geri döndürülemez."),
                new Riddle("Ne kadar çok paylaşılırsa o kadar çoğalır. Ben neyim?", "Bilgi", "İpucu: Öğrenildikçe artar."),
                new Riddle("Hangi ağaç asla yaprak dökmez?", "Meşe", "İpucu: Sağlam ve dayanıklıdır."),
                new Riddle("Her zaman ileri gider ama asla geri dönmez. Ben neyim?", "Zaman", "İpucu: Durmaz."),
                new Riddle("Ben büyürüm ama asla yaşlanmam. Ben neyim?", "Dağ", "İpucu: Yükseklik sembolüdür.")
        };
    }
}
